/**
// #if LBRN
 * LaserPost for LightBurn: Copyright (C) 2023 nuCarve
 *
 * A CAM post processor for creating LightBurn project(s) for laser (jet) operations.
// #else
 * LaserPost for SVG: Copyright (C) 2023 nuCarve
 *
 * A CAM post processor for creating SVG file(s) for laser (jet) operations.
// #endif
 * For more information, visit https://nucarve.com/laserpost.
 *
 * A shared source code base is used to build multiple versions of LaserPost, and this source
 * file is automatically generated.  DO NOT MODIFY THIS FILE.  Visit the nuCarve LaserPost
 * github site at https://github.com/nucarve/laserpost for the source code and release
 * instructions.
 *
 * This software is licensed under the MIT License:
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 *
 * Additional license and attribution requrements are included in subsections below.
 */

/**************************************************************************************
 *
 * Post-processor global kernel settings
 *
 *************************************************************************************/

// set up global parameters used by CAM to track the post processor
// #if LBRN
description = localize('LaserPost for LightBurn (VERSION_NUMBER)');
longDescription = localize('LaserPost for LightBurn (VERSION_NUMBER) generates .LBRN projects from CAM operations.');
// #else
description = localize('LaserPost for SVG (VERSION_NUMBER)');
longDescription = localize('LaserPost for LightBurn (VERSION_NUMBER) generates .SVG files from CAM operations.');
// #endif
vendor = 'nuCarve';
vendorUrl = 'https://nucarve.com/laserpost';
legal = 'Copyright (C) 2023 by nuCarve';
// #if LBRN
extension = 'lbrn';
// #else
extension = 'svg';
// #endif
certificationLevel = 2;

capabilities = CAPABILITY_JET;
tolerance = spatial(0.0001, MM);
minimumChordLength = spatial(0.01, MM);
minimumCircularRadius = spatial(0.01, MM);
maximumCircularRadius = spatial(99999, MM);
minimumCircularSweep = toRad(0.01);
maximumCircularSweep = Math.PI * 2;
allowHelicalMoves = false;
allowedCircularPlanes = 1 << PLANE_XY;

// define global variables used by LaserPost
let semVer = 'VERSION_NUMBER';
const codeMoreInformation = localize(
  'Visit https://nucarve.com/laserpost for software, instructions and instructional videos.'
);
let generatedBy;
// #if LBRN
generatedBy = localize(
  'Project generated by LaserPost for LightBurn (version VERSION_NUMBER).'
);
// #else
generatedBy = localize(
  'SVG file generated by LaserPost for SVG (version VERSION_NUMBER).  '
);
// #endif

setCodePage('ascii');
